services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php83_objective
    ports:
      - "8080:8080"
    volumes:
      - ./src:/application
    working_dir: /application
